apiVersion: v1
kind: Service
metadata:
  name: myflaskapp-svc
  labels:
    app: myflaskapp
spec:
  type: LoadBalancer 
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: myflaskapp
